# Generated by Django 5.0.6 on 2025-09-13 05:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_huerta', '0014_alter_huerta_options_alter_huertarentada_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['nombre'], name='idx_bodega_nombre'), models.Index(fields=['is_active'], name='idx_bodega_is_active'), models.Index(fields=['archivado_en'], name='idx_bodega_archivado')],
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('camion_numero', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('CLASIFICADO', 'Clasificado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('placas', models.CharField(blank=True, max_length=20, null=True)),
                ('chofer', models.CharField(blank=True, max_length=100, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones', to='gestion_bodega.bodega')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camiones', to=settings.AUTH_USER_MODEL)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones', to='gestion_huerta.temporada')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CierreSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_semana', models.CharField(max_length=10)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_semanales', to='gestion_bodega.bodega')),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_semanales', to='gestion_huerta.temporada')),
            ],
            options={
                'ordering': ['-fecha_desde', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PLASTICO', 'Plástico'), ('MADERA', 'Madera')], max_length=8)),
                ('calidad', models.CharField(max_length=8)),
                ('tipo_mango', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('normalizado_desde', models.CharField(blank=True, max_length=8, null=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='gestion_bodega.camion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompraMadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('proveedor', models.CharField(max_length=255)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_madera', to='gestion_bodega.bodega')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_madera', to='gestion_huerta.temporada')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AbonoMadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='gestion_bodega.compramadera')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumibles', to='gestion_bodega.bodega')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumibles', to='gestion_huerta.temporada')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioPlastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.CharField(choices=[('PRIMERA', 'Primera'), ('TERCERA', 'Tercera'), ('NIÑO', 'Niño'), ('ROÑA', 'Roña'), ('MADURO', 'Maduro'), ('SEGUNDA', 'Segunda')], max_length=8)),
                ('tipo_mango', models.CharField(max_length=50)),
                ('propietario_tipo', models.CharField(choices=[('BODEGA', 'Bodega'), ('CLIENTE', 'Cliente')], default='BODEGA', max_length=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_plastico', to='gestion_bodega.bodega')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_plastico', to=settings.AUTH_USER_MODEL)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_plastico', to='gestion_huerta.temporada')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PARCIAL', 'Parcial'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=10)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion_bodega.bodega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion_huerta.temporada')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PLASTICO', 'Plástico'), ('MADERA', 'Madera')], max_length=8)),
                ('calidad', models.CharField(max_length=8)),
                ('tipo_mango', models.CharField(max_length=50)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_surtida', models.PositiveIntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='gestion_bodega.pedido')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SurtidoRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surtidos', to='gestion_bodega.clasificacioncamion')),
                ('renglon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surtidos', to='gestion_bodega.pedidorenglon')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['bodega', 'temporada', 'camion_numero'], name='idx_camion_unique'),
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['fecha'], name='idx_camion_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='camion',
            unique_together={('bodega', 'temporada', 'camion_numero')},
        ),
        migrations.AddIndex(
            model_name='cierresemanal',
            index=models.Index(fields=['bodega', 'temporada', 'iso_semana'], name='idx_cierre_semanal_key'),
        ),
        migrations.AlterUniqueTogether(
            name='cierresemanal',
            unique_together={('bodega', 'temporada', 'iso_semana')},
        ),
        migrations.AddIndex(
            model_name='clasificacioncamion',
            index=models.Index(fields=['camion', 'material'], name='idx_clas_camion_mat'),
        ),
        migrations.AddIndex(
            model_name='compramadera',
            index=models.Index(fields=['bodega', 'temporada', 'proveedor'], name='idx_compra_madera_key'),
        ),
        migrations.AddIndex(
            model_name='abonomadera',
            index=models.Index(fields=['compra', 'fecha'], name='idx_abono_madera_key'),
        ),
        migrations.AddIndex(
            model_name='consumible',
            index=models.Index(fields=['bodega', 'temporada', 'concepto'], name='idx_consumible_key'),
        ),
        migrations.AddIndex(
            model_name='inventarioplastico',
            index=models.Index(fields=['bodega', 'temporada', 'calidad', 'propietario_tipo', 'cliente'], name='idx_inv_plastico_key'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioplastico',
            unique_together={('bodega', 'temporada', 'calidad', 'tipo_mango', 'propietario_tipo', 'cliente')},
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['bodega', 'temporada', 'cliente', 'estado'], name='idx_pedido_key'),
        ),
        migrations.AddIndex(
            model_name='pedidorenglon',
            index=models.Index(fields=['pedido', 'material', 'calidad'], name='idx_pedido_renglon_key'),
        ),
        migrations.AddIndex(
            model_name='surtidorenglon',
            index=models.Index(fields=['renglon', 'clasificacion'], name='idx_surtido_key'),
        ),
    ]
