# Generated by Django 5.0.6 on 2025-09-18 10:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoMadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(blank=True, default='', max_length=30)),
                ('saldo_resultante', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('material', models.CharField(choices=[('MADERA', 'Madera'), ('PLASTICO', 'Plástico')], max_length=10)),
                ('calidad', models.CharField(max_length=12)),
                ('tipo_mango', models.CharField(max_length=80)),
                ('cantidad_cajas', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=120)),
                ('alias', models.CharField(blank=True, default='', max_length=60)),
                ('rfc', models.CharField(blank=True, default='', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('notas', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompraMadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('proveedor_nombre', models.CharField(max_length=120)),
                ('cantidad_cajas', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('concepto', models.CharField(max_length=120)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioPlastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('calidad', models.CharField(choices=[('PRIMERA', 'Primera'), ('TERCERA', 'Tercera'), ('NINIO', 'Niño'), ('RONIA', 'Roña'), ('MADURO', 'Maduro')], max_length=12)),
                ('tipo_mango', models.CharField(blank=True, default='', max_length=80)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPlastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('referencia_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('referencia_id', models.CharField(blank=True, default='', max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PARCIAL', 'Parcial'), ('SURTIDO', 'Surtido'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=12)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('material', models.CharField(choices=[('MADERA', 'Madera'), ('PLASTICO', 'Plástico')], max_length=10)),
                ('calidad', models.CharField(max_length=12)),
                ('tipo_mango', models.CharField(blank=True, default='', max_length=80)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_surtida', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('huertero_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_mango', models.CharField(max_length=80)),
                ('cajas_campo', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SurtidoRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemporadaBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('año', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-año', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['nombre'], name='idx_bod_nombre'), models.Index(fields=['is_active'], name='idx_bod_is_active'), models.Index(fields=['archivado_en'], name='idx_bod_archivado')],
            },
        ),
        migrations.CreateModel(
            name='CamionSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=12)),
                ('fecha_salida', models.DateField(default=django.utils.timezone.now)),
                ('placas', models.CharField(blank=True, default='', max_length=20)),
                ('chofer', models.CharField(blank=True, default='', max_length=80)),
                ('destino', models.CharField(blank=True, default='', max_length=120)),
                ('receptor', models.CharField(blank=True, default='', max_length=120)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones', to='gestion_bodega.bodega')),
            ],
            options={
                'ordering': ['-fecha_salida', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CamionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('material', models.CharField(choices=[('MADERA', 'Madera'), ('PLASTICO', 'Plástico')], max_length=10)),
                ('calidad', models.CharField(max_length=12)),
                ('tipo_mango', models.CharField(blank=True, default='', max_length=80)),
                ('cantidad_cajas', models.PositiveIntegerField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion_bodega.camionsalida')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CierreSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('iso_semana', models.CharField(max_length=10)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='gestion_bodega.bodega')),
            ],
            options={
                'ordering': ['-fecha_desde', '-id'],
            },
        ),
    ]
