# Generated by Django 5.0.6 on 2025-09-13 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0001_initial'),
        ('gestion_huerta', '0014_alter_huerta_options_alter_huertarentada_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PLASTICO', 'Plástico'), ('MADERA', 'Madera')], max_length=10)),
                ('calidad', models.CharField(max_length=10)),
                ('tipo_mango', models.CharField(blank=True, max_length=80, null=True)),
                ('cantidad_cajas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CamionSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('placas', models.CharField(blank=True, max_length=20, null=True)),
                ('chofer', models.CharField(blank=True, max_length=120, null=True)),
                ('destino', models.CharField(blank=True, max_length=120, null=True)),
                ('recibe', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo_mango', models.CharField(max_length=80)),
                ('material', models.CharField(choices=[('PLASTICO', 'Plástico'), ('MADERA', 'Madera')], max_length=10)),
                ('calidad_entrada', models.CharField(choices=[('PRIMERA', 'Primera'), ('TERCERA', 'Tercera'), ('NINO', 'Niño'), ('RONIA', 'Roña'), ('MADURO', 'Maduro'), ('SEGUNDA', 'Segunda (normaliza a Primera)'), ('EXTRA', 'Extra (normaliza a Primera)'), ('EXTRA', 'Extra'), ('PRIMERA', 'Primera'), ('SEGUNDA', 'Segunda'), ('TERCERA', 'Tercera'), ('CUARTA', 'Cuarta'), ('NINO', 'Niño'), ('RONIA', 'Roña'), ('MADURO', 'Maduro')], max_length=10)),
                ('calidad_stock', models.CharField(max_length=10)),
                ('cantidad_cajas', models.PositiveIntegerField()),
                ('normalizado_desde', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPlastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('huertero_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_mango', models.CharField(max_length=80)),
                ('cajas_campo', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='camion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='camion',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='temporada',
        ),
        migrations.RemoveField(
            model_name='clasificacioncamion',
            name='camion',
        ),
        migrations.RemoveField(
            model_name='surtidorenglon',
            name='clasificacion',
        ),
        migrations.AlterModelOptions(
            name='abonomadera',
            options={'ordering': ['-fecha', 'id']},
        ),
        migrations.AlterModelOptions(
            name='bodega',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='cierresemanal',
            options={'ordering': ['-fecha_desde', 'id']},
        ),
        migrations.AlterModelOptions(
            name='compramadera',
            options={'ordering': ['-fecha', 'id']},
        ),
        migrations.AlterModelOptions(
            name='consumible',
            options={'ordering': ['-fecha', 'id']},
        ),
        migrations.AlterModelOptions(
            name='inventarioplastico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha', 'id']},
        ),
        migrations.AlterModelOptions(
            name='pedidorenglon',
            options={},
        ),
        migrations.AlterModelOptions(
            name='surtidorenglon',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='abonomadera',
            name='idx_abono_madera_key',
        ),
        migrations.RemoveIndex(
            model_name='bodega',
            name='idx_bodega_nombre',
        ),
        migrations.RemoveIndex(
            model_name='bodega',
            name='idx_bodega_is_active',
        ),
        migrations.RemoveIndex(
            model_name='bodega',
            name='idx_bodega_archivado',
        ),
        migrations.RemoveIndex(
            model_name='cierresemanal',
            name='idx_cierre_semanal_key',
        ),
        migrations.RemoveIndex(
            model_name='compramadera',
            name='idx_compra_madera_key',
        ),
        migrations.RemoveIndex(
            model_name='consumible',
            name='idx_consumible_key',
        ),
        migrations.RemoveIndex(
            model_name='inventarioplastico',
            name='idx_inv_plastico_key',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='idx_pedido_key',
        ),
        migrations.RemoveIndex(
            model_name='pedidorenglon',
            name='idx_pedido_renglon_key',
        ),
        migrations.RemoveIndex(
            model_name='surtidorenglon',
            name='idx_surtido_key',
        ),
        migrations.RenameField(
            model_name='compramadera',
            old_name='cantidad',
            new_name='cantidad_cajas',
        ),
        migrations.RemoveField(
            model_name='compramadera',
            name='archivado_en',
        ),
        migrations.RemoveField(
            model_name='compramadera',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='consumible',
            name='archivado_en',
        ),
        migrations.RemoveField(
            model_name='consumible',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='archivado_en',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='surtidorenglon',
            name='fecha',
        ),
        migrations.AddField(
            model_name='abonomadera',
            name='metodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='abonomadera',
            name='saldo_resultante',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compramadera',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surtidorenglon',
            name='request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cierresemanal',
            name='locked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cierresemanal',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cierresemanal',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_semanales_bodega', to='gestion_huerta.temporada'),
        ),
        migrations.AlterField(
            model_name='compramadera',
            name='proveedor',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='compramadera',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='compramadera',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_madera_bodega', to='gestion_huerta.temporada'),
        ),
        migrations.AlterField(
            model_name='consumible',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='consumible',
            name='concepto',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='consumible',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumibles_bodega', to='gestion_huerta.temporada'),
        ),
        migrations.AlterField(
            model_name='consumible',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventarioplastico',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_plastico', to='gestion_bodega.bodega'),
        ),
        migrations.AlterField(
            model_name='inventarioplastico',
            name='calidad',
            field=models.CharField(choices=[('PRIMERA', 'Primera'), ('TERCERA', 'Tercera'), ('NINO', 'Niño'), ('RONIA', 'Roña'), ('MADURO', 'Maduro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventarioplastico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventarioplastico',
            name='propietario_tipo',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('CLIENTE', 'Cliente')], default='BODEGA', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventarioplastico',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_plastico_bodega', to='gestion_huerta.temporada'),
        ),
        migrations.AlterField(
            model_name='inventarioplastico',
            name='tipo_mango',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_bodega', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_bodega', to='gestion_huerta.temporada'),
        ),
        migrations.AlterField(
            model_name='pedidorenglon',
            name='calidad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidorenglon',
            name='material',
            field=models.CharField(choices=[('PLASTICO', 'Plástico'), ('MADERA', 'Madera')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidorenglon',
            name='tipo_mango',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='compramadera',
            index=models.Index(fields=['bodega', 'temporada', 'proveedor', 'fecha'], name='gestion_bod_bodega__82bba2_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidorenglon',
            index=models.Index(fields=['pedido', 'material', 'calidad', 'tipo_mango'], name='gestion_bod_pedido__602480_idx'),
        ),
        migrations.AddField(
            model_name='camionsalida',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones', to='gestion_bodega.bodega'),
        ),
        migrations.AddField(
            model_name='camionsalida',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones_bodega', to='gestion_huerta.temporada'),
        ),
        migrations.AddField(
            model_name='camionitem',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion_bodega.camionsalida'),
        ),
        migrations.AddField(
            model_name='clasificacionempaque',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones', to='gestion_bodega.bodega'),
        ),
        migrations.AddField(
            model_name='clasificacionempaque',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones_bodega', to='gestion_huerta.temporada'),
        ),
        migrations.AddField(
            model_name='surtidorenglon',
            name='origen_clasificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='surtidos', to='gestion_bodega.clasificacionempaque'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='surtidorenglon',
            index=models.Index(fields=['renglon', 'origen_clasificacion'], name='gestion_bod_renglon_07fe91_idx'),
        ),
        migrations.AddField(
            model_name='movimientoplastico',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='gestion_bodega.inventarioplastico'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='gestion_bodega.bodega'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='huerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_huerta.huerta'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_bodega', to='gestion_huerta.temporada'),
        ),
        migrations.AddField(
            model_name='clasificacionempaque',
            name='recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones', to='gestion_bodega.recepcion'),
        ),
        migrations.DeleteModel(
            name='Camion',
        ),
        migrations.DeleteModel(
            name='ClasificacionCamion',
        ),
        migrations.AlterUniqueTogether(
            name='camionsalida',
            unique_together={('bodega', 'temporada', 'numero')},
        ),
        migrations.AddIndex(
            model_name='recepcion',
            index=models.Index(fields=['bodega', 'temporada', 'fecha'], name='gestion_bod_bodega__2bc141_idx'),
        ),
        migrations.AddIndex(
            model_name='clasificacionempaque',
            index=models.Index(fields=['bodega', 'temporada', 'fecha'], name='gestion_bod_bodega__c3563e_idx'),
        ),
    ]
