# Generated by Django 5.0.6 on 2025-09-18 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_bodega', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierresemanal',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_bodega_lock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clasificacionempaque',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones', to='gestion_bodega.bodega'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='idx_cli_nombre'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['rfc'], name='idx_cli_rfc'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['is_active'], name='idx_cli_is_active'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('nombre', 'rfc'), name='uniq_cliente_bodega_nom_rfc'),
        ),
        migrations.AddField(
            model_name='compramadera',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_madera', to='gestion_bodega.bodega'),
        ),
        migrations.AddField(
            model_name='abonomadera',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='gestion_bodega.compramadera'),
        ),
        migrations.AddField(
            model_name='consumible',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumibles', to='gestion_bodega.bodega'),
        ),
        migrations.AddField(
            model_name='inventarioplastico',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_plastico', to='gestion_bodega.bodega'),
        ),
        migrations.AddField(
            model_name='inventarioplastico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_plastico', to='gestion_bodega.cliente'),
        ),
        migrations.AddField(
            model_name='movimientoplastico',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_bodega.inventarioplastico'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion_bodega.bodega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_bodega', to='gestion_bodega.cliente'),
        ),
        migrations.AddField(
            model_name='pedidorenglon',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='gestion_bodega.pedido'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='gestion_bodega.bodega'),
        ),
        migrations.AddField(
            model_name='clasificacionempaque',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones', to='gestion_bodega.recepcion'),
        ),
        migrations.AddField(
            model_name='surtidorenglon',
            name='origen_clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surtidos', to='gestion_bodega.clasificacionempaque'),
        ),
        migrations.AddField(
            model_name='surtidorenglon',
            name='renglon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surtidos', to='gestion_bodega.pedidorenglon'),
        ),
        migrations.AddField(
            model_name='temporadabodega',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='gestion_bodega.bodega'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='gestion_bodega.temporadabodega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='gestion_bodega.temporadabodega'),
        ),
        migrations.AddField(
            model_name='inventarioplastico',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_plastico', to='gestion_bodega.temporadabodega'),
        ),
        migrations.AddField(
            model_name='consumible',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumibles', to='gestion_bodega.temporadabodega'),
        ),
        migrations.AddField(
            model_name='compramadera',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_madera', to='gestion_bodega.temporadabodega'),
        ),
        migrations.AddField(
            model_name='clasificacionempaque',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='gestion_bodega.temporadabodega'),
        ),
        migrations.AddField(
            model_name='cierresemanal',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='gestion_bodega.temporadabodega'),
        ),
        migrations.AddField(
            model_name='camionsalida',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camiones', to='gestion_bodega.temporadabodega'),
        ),
        migrations.AddIndex(
            model_name='camionitem',
            index=models.Index(fields=['camion'], name='idx_cami_camion'),
        ),
        migrations.AddIndex(
            model_name='camionitem',
            index=models.Index(fields=['material', 'calidad'], name='idx_cami_mat_cal'),
        ),
        migrations.AddIndex(
            model_name='abonomadera',
            index=models.Index(fields=['compra', 'fecha'], name='idx_abm_compra_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientoplastico',
            index=models.Index(fields=['inventario', 'fecha'], name='idx_movp_inv_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientoplastico',
            index=models.Index(fields=['tipo'], name='idx_movp_tipo'),
        ),
        migrations.AddIndex(
            model_name='pedidorenglon',
            index=models.Index(fields=['pedido', 'material', 'calidad'], name='idx_pedr_pmc'),
        ),
        migrations.AddIndex(
            model_name='surtidorenglon',
            index=models.Index(fields=['renglon', 'origen_clasificacion'], name='idx_sur_reng_origen'),
        ),
        migrations.AddIndex(
            model_name='temporadabodega',
            index=models.Index(fields=['año'], name='idx_tb_año'),
        ),
        migrations.AddIndex(
            model_name='temporadabodega',
            index=models.Index(fields=['bodega'], name='idx_tb_bodega'),
        ),
        migrations.AddIndex(
            model_name='temporadabodega',
            index=models.Index(fields=['finalizada'], name='idx_tb_finalizada'),
        ),
        migrations.AddIndex(
            model_name='temporadabodega',
            index=models.Index(fields=['is_active'], name='idx_tb_is_active'),
        ),
        migrations.AlterUniqueTogether(
            name='temporadabodega',
            unique_together={('año', 'bodega')},
        ),
        migrations.AddIndex(
            model_name='recepcion',
            index=models.Index(fields=['bodega', 'temporada', 'fecha'], name='idx_rec_bod_temp_fecha'),
        ),
        migrations.AddIndex(
            model_name='recepcion',
            index=models.Index(fields=['tipo_mango'], name='idx_rec_tipo_mango'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['bodega', 'temporada', 'cliente', 'estado'], name='idx_ped_claves'),
        ),
        migrations.AddIndex(
            model_name='inventarioplastico',
            index=models.Index(fields=['bodega', 'temporada', 'cliente'], name='idx_invp_bod_temp_cli'),
        ),
        migrations.AddIndex(
            model_name='inventarioplastico',
            index=models.Index(fields=['calidad', 'tipo_mango'], name='idx_invp_cal_tm'),
        ),
        migrations.AddConstraint(
            model_name='inventarioplastico',
            constraint=models.UniqueConstraint(fields=('bodega', 'temporada', 'cliente', 'calidad', 'tipo_mango'), name='uniq_inv_plastico_key'),
        ),
        migrations.AddIndex(
            model_name='consumible',
            index=models.Index(fields=['bodega', 'temporada', 'fecha'], name='idx_con_bod_temp_fecha'),
        ),
        migrations.AddIndex(
            model_name='consumible',
            index=models.Index(fields=['concepto'], name='idx_con_concepto'),
        ),
        migrations.AddIndex(
            model_name='compramadera',
            index=models.Index(fields=['bodega', 'temporada'], name='idx_cm_bod_temp'),
        ),
        migrations.AddIndex(
            model_name='compramadera',
            index=models.Index(fields=['proveedor_nombre'], name='idx_cm_proveedor'),
        ),
        migrations.AddIndex(
            model_name='clasificacionempaque',
            index=models.Index(fields=['bodega', 'temporada', 'fecha'], name='idx_emp_bod_temp_fecha'),
        ),
        migrations.AddIndex(
            model_name='clasificacionempaque',
            index=models.Index(fields=['material', 'calidad'], name='idx_emp_mat_cal'),
        ),
        migrations.AddIndex(
            model_name='clasificacionempaque',
            index=models.Index(fields=['tipo_mango'], name='idx_emp_tipo_mango'),
        ),
        migrations.AddIndex(
            model_name='cierresemanal',
            index=models.Index(fields=['bodega', 'temporada', 'fecha_desde', 'fecha_hasta'], name='idx_cierre_rango'),
        ),
        migrations.AddConstraint(
            model_name='cierresemanal',
            constraint=models.UniqueConstraint(fields=('bodega', 'temporada', 'iso_semana'), name='uniq_cierre_semana_bod_temp'),
        ),
        migrations.AddIndex(
            model_name='camionsalida',
            index=models.Index(fields=['bodega', 'temporada', 'numero'], name='idx_cam_bod_temp_num'),
        ),
        migrations.AddIndex(
            model_name='camionsalida',
            index=models.Index(fields=['estado'], name='idx_cam_estado'),
        ),
        migrations.AddConstraint(
            model_name='camionsalida',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('bodega', 'temporada', 'numero'), name='uniq_camion_numero_por_bodega_temporada'),
        ),
    ]
