# Generated by Django 5.0.6 on 2025-10-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temporadabodega',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='temporadabodega',
            constraint=models.UniqueConstraint(condition=models.Q(('finalizada', False)), fields=('año', 'bodega'), name='uniq_temporadabodega_activa'),
        ),
    ]
