# Generated by Django 5.0.6 on 2025-11-02 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0003_alter_temporadabodega_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierresemanal',
            options={'ordering': ['-fecha_desde', '-id'], 'permissions': (('close_week', 'Puede cerrar semana'), ('view_dashboard', 'Puede ver el tablero de bodega'))},
        ),
        migrations.AlterModelOptions(
            name='temporadabodega',
            options={'ordering': ['-año', '-id'], 'permissions': (('finalize_temporadabodega', 'Puede finalizar temporada de bodega'),)},
        ),
        migrations.RemoveConstraint(
            model_name='cierresemanal',
            name='uniq_cierre_semana_bod_temp',
        ),
        migrations.AlterField(
            model_name='cierresemanal',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cierresemanal',
            name='iso_semana',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cierresemanal',
            index=models.Index(fields=['iso_semana'], name='idx_cierre_iso'),
        ),
        migrations.AddConstraint(
            model_name='cierresemanal',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_hasta__isnull', True)), fields=('bodega', 'temporada'), name='uniq_cierre_semana_abierta_bod_temp'),
        ),
    ]
