# Generated by Django 5.0.6 on 2025-11-10 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0004_alter_cierresemanal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacionempaque',
            name='semana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones', to='gestion_bodega.cierresemanal'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='semana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='gestion_bodega.cierresemanal'),
        ),
    ]
