# Generated by Django 5.0.6 on 2025-12-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0005_clasificacionempaque_semana_recepcion_semana'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clasificacionempaque',
            index=models.Index(fields=['bodega', 'temporada', 'semana', 'fecha'], name='idx_emp_ctx_semana_fecha'),
        ),
        migrations.AddIndex(
            model_name='recepcion',
            index=models.Index(fields=['bodega', 'temporada', 'semana', 'fecha'], name='idx_rec_ctx_semana_fecha'),
        ),
    ]
