# Generated by Django 5.0.6 on 2025-12-21 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0006_clasificacionempaque_idx_emp_ctx_semana_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cierresemanal',
            name='uniq_cierre_semana_abierta_bod_temp',
        ),
        migrations.AlterField(
            model_name='inventarioplastico',
            name='calidad',
            field=models.CharField(choices=[('PRIMERA', 'Primera'), ('TERCERA', 'Tercera'), ('NINIO', 'Niño'), ('RONIA', 'Roña'), ('MADURO', 'Maduro'), ('MERMA', 'Merma')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='cierresemanal',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_hasta__isnull', True), ('is_active', True)), fields=('bodega', 'temporada'), name='uniq_cierre_semana_abierta_bod_temp'),
        ),
        migrations.AddConstraint(
            model_name='clasificacionempaque',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('recepcion', 'material', 'calidad'), name='uniq_emp_linea_activa_por_recepcion'),
        ),
    ]
