# Generated by Django 5.0.6 on 2025-12-31 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0007_remove_cierresemanal_uniq_cierre_semana_abierta_bod_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='LoteBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('codigo_lote', models.CharField(max_length=50)),
                ('origen_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='gestion_bodega.bodega')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_creados', to='gestion_bodega.cierresemanal')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='gestion_bodega.temporadabodega')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='clasificacionempaque',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones', to='gestion_bodega.lotebodega'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='gestion_bodega.lotebodega'),
        ),
        migrations.AddIndex(
            model_name='lotebodega',
            index=models.Index(fields=['bodega', 'temporada', 'codigo_lote'], name='idx_lote_bt_codigo'),
        ),
        migrations.AddConstraint(
            model_name='lotebodega',
            constraint=models.UniqueConstraint(fields=('bodega', 'temporada', 'codigo_lote'), name='uniq_lote_codigo_por_temporada'),
        ),
    ]
