# Generated by Django 5.0.6 on 2025-12-31 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0008_alter_bodega_nombre_lotebodega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamionConsumoEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='gestion_bodega.camionsalida')),
                ('clasificacion_empaque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_camion', to='gestion_bodega.clasificacionempaque')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['camion', 'clasificacion_empaque'], name='idx_cce_camion_clasif')],
            },
        ),
    ]
