# Generated by Django 5.0.6 on 2025-12-31 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0009_camionconsumoempaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionsalida',
            name='semana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camiones', to='gestion_bodega.cierresemanal'),
        ),
        migrations.AddIndex(
            model_name='camionsalida',
            index=models.Index(fields=['bodega', 'temporada', 'semana', 'fecha_salida'], name='idx_cam_ctx_semana_fecha'),
        ),
    ]
