# Generated by Django 5.0.6 on 2026-01-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0010_camionsalida_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionsalida',
            name='folio',
            field=models.CharField(blank=True, default='', help_text='Folio único generado al confirmar (formato: BOD-X-TX-WX-CXXXXX)', max_length=50),
        ),
    ]
