# Generated by Django 5.0.6 on 2026-02-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0011_add_folio_camion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camionsalida',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
