# Generated by Django 5.0.6 on 2026-02-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0012_alter_camionsalida_fecha_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='compramadera',
            name='hay_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='compramadera',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0, help_text='Cajas físicas disponibles actualmente'),
        ),
        migrations.AddField(
            model_name='compramadera',
            name='stock_inicial',
            field=models.PositiveIntegerField(default=0, help_text='Cajas físicas compradas'),
        ),
        migrations.CreateModel(
            name='ConsumoMadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_madera', to='gestion_bodega.clasificacionempaque')),
                ('compra_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_despachados', to='gestion_bodega.compramadera')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['clasificacion', 'compra_origen'], name='idx_cons_mad_clas_compra')],
            },
        ),
    ]
