# Generated by Django 5.0.6 on 2026-02-20 04:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0012_alter_camionsalida_fecha_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoplastico',
            name='inventario',
        ),
        migrations.CreateModel(
            name='InventarioEnvases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('material', models.CharField(choices=[('MADERA', 'Madera'), ('PLASTICO', 'Plástico')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_envases', to='gestion_bodega.bodega')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_envases', to='gestion_bodega.cliente')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_envases', to='gestion_bodega.temporadabodega')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoEnvases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('referencia_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('referencia_id', models.CharField(blank=True, default='', max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_bodega.inventarioenvases')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='InventarioPlastico',
        ),
        migrations.DeleteModel(
            name='MovimientoPlastico',
        ),
        migrations.AddIndex(
            model_name='inventarioenvases',
            index=models.Index(fields=['bodega', 'temporada', 'cliente', 'material'], name='idx_inve_bod_temp_cli_mat'),
        ),
        migrations.AddConstraint(
            model_name='inventarioenvases',
            constraint=models.UniqueConstraint(fields=('bodega', 'temporada', 'cliente', 'material'), name='uniq_inv_envases_key'),
        ),
        migrations.AddIndex(
            model_name='movimientoenvases',
            index=models.Index(fields=['inventario', 'fecha'], name='idx_move_inv_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientoenvases',
            index=models.Index(fields=['tipo'], name='idx_move_tipo'),
        ),
    ]
