# Generated by Django 5.0.6 on 2026-03-08 20:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0013_compramadera_hay_stock_compramadera_stock_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramadera',
            name='cantidad_cajas',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compramadera',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cajas físicas disponibles actualmente', max_digits=12),
        ),
        migrations.AlterField(
            model_name='compramadera',
            name='stock_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cajas físicas compradas', max_digits=12),
        ),
        migrations.AlterField(
            model_name='consumomadera',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
