# Generated by Django 5.0.6 on 2026-03-08 23:08
# Custom: uses SeparateDatabaseAndState to handle tables/columns
# that may already have been dropped in the live MySQL schema.

from django.db import migrations


IGNORED_MYSQL_DROP_ERRORS = {1072, 1091}


def _should_ignore_mysql_drop_error(exc):
    args = getattr(exc, "args", ())
    return bool(args) and args[0] in IGNORED_MYSQL_DROP_ERRORS


def _column_exists(connection, table, column):
    with connection.cursor() as cur:
        cur.execute(
            "SELECT COUNT(*) FROM information_schema.columns "
            "WHERE table_schema = DATABASE() AND table_name = %s AND column_name = %s",
            [table, column],
        )
        return cur.fetchone()[0] > 0


def _table_exists(connection, table):
    with connection.cursor() as cur:
        cur.execute(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = DATABASE() AND table_name = %s",
            [table],
        )
        return cur.fetchone()[0] > 0


def _drop_foreign_keys(connection, table, column):
    with connection.cursor() as cur:
        cur.execute(
            "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE table_schema = DATABASE() AND table_name = %s "
            "AND column_name = %s AND REFERENCED_TABLE_NAME IS NOT NULL",
            [table, column],
        )
        for (fk_name,) in cur.fetchall():
            try:
                cur.execute(f"ALTER TABLE `{table}` DROP FOREIGN KEY `{fk_name}`")
            except Exception as exc:
                if not _should_ignore_mysql_drop_error(exc):
                    raise


def _drop_secondary_indexes(connection, table, column):
    with connection.cursor() as cur:
        cur.execute(
            "SELECT DISTINCT INDEX_NAME FROM information_schema.STATISTICS "
            "WHERE table_schema = DATABASE() AND table_name = %s "
            "AND column_name = %s AND INDEX_NAME <> 'PRIMARY'",
            [table, column],
        )
        for (index_name,) in cur.fetchall():
            try:
                cur.execute(f"ALTER TABLE `{table}` DROP INDEX `{index_name}`")
            except Exception as exc:
                if not _should_ignore_mysql_drop_error(exc):
                    raise


def safe_drop_fk_and_column(apps, schema_editor):
    """
    Drop legacy tables in dependency-safe order.

    These models are removed from state in the same migration, so dropping whole
    tables is both simpler and more robust than trying to dismantle individual
    foreign keys/indexes in drifted MySQL schemas.
    """
    connection = schema_editor.connection

    tables_to_drop = [
        "gestion_bodega_camionitem",
        "gestion_bodega_surtidorenglon",
        "gestion_bodega_pedidorenglon",
        "gestion_bodega_pedido",
        "gestion_bodega_movimientoplastico",
        "gestion_bodega_inventarioplastico",
        "gestion_bodega_cliente",
    ]
    with connection.cursor() as cur:
        for table in tables_to_drop:
            if _table_exists(connection, table):
                cur.execute(f"DROP TABLE IF EXISTS `{table}`")


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0014_alter_compramadera_cantidad_cajas_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # The DB operations are handled by our safe_drop function
            database_operations=[
                migrations.RunPython(safe_drop_fk_and_column, migrations.RunPython.noop),
            ],
            # The state operations tell Django "these models no longer exist"
            state_operations=[
                migrations.RemoveField(model_name='pedido', name='cliente'),
                migrations.RemoveField(model_name='inventarioplastico', name='cliente'),
                migrations.RemoveField(model_name='inventarioplastico', name='bodega'),
                migrations.RemoveField(model_name='inventarioplastico', name='temporada'),
                migrations.RemoveField(model_name='movimientoplastico', name='inventario'),
                migrations.RemoveField(model_name='pedido', name='bodega'),
                migrations.RemoveField(model_name='pedido', name='temporada'),
                migrations.RemoveField(model_name='pedidorenglon', name='pedido'),
                migrations.RemoveField(model_name='surtidorenglon', name='renglon'),
                migrations.RemoveField(model_name='surtidorenglon', name='origen_clasificacion'),
                migrations.DeleteModel(name='CamionItem'),
                migrations.DeleteModel(name='Cliente'),
                migrations.DeleteModel(name='InventarioPlastico'),
                migrations.DeleteModel(name='MovimientoPlastico'),
                migrations.DeleteModel(name='Pedido'),
                migrations.DeleteModel(name='PedidoRenglon'),
                migrations.DeleteModel(name='SurtidoRenglon'),
            ],
        ),
    ]
