# Generated by Django 5.0.6 on 2026-03-15 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodega', '0015_remove_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonomadera',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='consumible',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='temporadabodega',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
