# Generated by Django 5.0.6 on 2025-04-08 08:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Huerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('variedades', models.CharField(max_length=255)),
                ('historial', models.TextField()),
                ('hectareas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HuertaRentada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('variedades', models.CharField(max_length=255)),
                ('historial', models.TextField()),
                ('hectareas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('monto_renta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido.', regex='^\\+?\\d{7,15}$')])),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('huerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosechas_huerta', to='gestion_huerta.huerta')),
                ('huerta_rentada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosechas_rentada', to='gestion_huerta.huertarentada')),
            ],
        ),
        migrations.CreateModel(
            name='InformeProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('variedad_mango', models.CharField(max_length=100)),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('editable', 'Editable'), ('revision', 'Revisión'), ('finalizado', 'Finalizado')], default='editable', max_length=20)),
                ('bloqueado', models.BooleanField(default=False)),
                ('huerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huerta')),
            ],
        ),
        migrations.CreateModel(
            name='InversionesHuerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('gastos_insumos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('gastos_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.categoriainversion')),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.cosecha')),
                ('huerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huerta')),
            ],
        ),
        migrations.AddField(
            model_name='huertarentada',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.propietario'),
        ),
        migrations.AddField(
            model_name='huerta',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.propietario'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('num_cajas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_por_caja', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo_mango', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('gasto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='gestion_huerta.cosecha')),
            ],
        ),
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['nombre'], name='gestion_hue_nombre_67cfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='informeproduccion',
            index=models.Index(fields=['fecha'], name='gestion_hue_fecha_4c4066_idx'),
        ),
        migrations.AddIndex(
            model_name='inversioneshuerta',
            index=models.Index(fields=['cosecha', 'categoria'], name='gestion_hue_cosecha_9d96c8_idx'),
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['nombre'], name='gestion_hue_nombre_a087e3_idx'),
        ),
        migrations.AddIndex(
            model_name='huerta',
            index=models.Index(fields=['nombre'], name='gestion_hue_nombre_237773_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_venta'], name='gestion_hue_fecha_v_ffb478_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cosecha'], name='gestion_hue_cosecha_cb1ff4_idx'),
        ),
    ]
