# Generated by Django 5.0.6 on 2025-09-18 10:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('variedades', models.CharField(max_length=255)),
                ('historial', models.TextField(blank=True, null=True)),
                ('hectareas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HuertaRentada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('variedades', models.CharField(max_length=255)),
                ('historial', models.TextField(blank=True, null=True)),
                ('hectareas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('monto_renta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['nombre'], name='gestion_hue_nombre_e01821_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('huerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='gestion_huerta.huerta')),
                ('huerta_rentada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosechas_rentadas', to='gestion_huerta.huertarentada')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['nombre'], name='idx_prop_nombre'), models.Index(fields=['apellidos'], name='idx_prop_apellidos'), models.Index(fields=['direccion'], name='idx_prop_direccion'), models.Index(fields=['is_active'], name='idx_prop_is_active'), models.Index(fields=['archivado_en'], name='idx_prop_archivado'), models.Index(fields=['nombre', 'apellidos'], name='idx_prop_nom_ape')],
            },
        ),
        migrations.AddField(
            model_name='huertarentada',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huertas_rentadas', to='gestion_huerta.propietario'),
        ),
        migrations.AddField(
            model_name='huerta',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huertas', to='gestion_huerta.propietario'),
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('huerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='gestion_huerta.huerta')),
                ('huerta_rentada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='gestion_huerta.huertarentada')),
            ],
            options={
                'ordering': ['-año'],
            },
        ),
        migrations.CreateModel(
            name='InversionesHuerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('gastos_insumos', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gastos_mano_obra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inversiones', to='gestion_huerta.categoriainversion')),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='gestion_huerta.cosecha')),
                ('huerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huerta')),
                ('huerta_rentada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huertarentada')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='gestion_huerta.temporada')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cosecha',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='gestion_huerta.temporada'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('num_cajas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_por_caja', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo_mango', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('gasto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='gestion_huerta.cosecha')),
                ('huerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huerta')),
                ('huerta_rentada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huertarentada')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='gestion_huerta.temporada')),
            ],
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['nombre'], name='idx_hr_nombre'),
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['ubicacion'], name='idx_hr_ubicacion'),
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['archivado_en'], name='idx_hr_archivado'),
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['is_active'], name='idx_hr_is_active'),
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['propietario', 'archivado_en'], name='idx_hr_prop_arch'),
        ),
        migrations.AlterUniqueTogether(
            name='huertarentada',
            unique_together={('nombre', 'ubicacion', 'propietario')},
        ),
        migrations.AddIndex(
            model_name='huerta',
            index=models.Index(fields=['nombre'], name='idx_huerta_nombre'),
        ),
        migrations.AddIndex(
            model_name='huerta',
            index=models.Index(fields=['archivado_en'], name='idx_huerta_archivado'),
        ),
        migrations.AddIndex(
            model_name='huerta',
            index=models.Index(fields=['is_active'], name='idx_huerta_is_active'),
        ),
        migrations.AddIndex(
            model_name='huerta',
            index=models.Index(fields=['propietario', 'archivado_en'], name='idx_huerta_prop_arch'),
        ),
        migrations.AlterUniqueTogether(
            name='huerta',
            unique_together={('nombre', 'ubicacion', 'propietario')},
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['año'], name='gestion_hue_año_4727d7_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['huerta'], name='gestion_hue_huerta__c45966_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['huerta_rentada'], name='gestion_hue_huerta__6402a6_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['is_active'], name='gestion_hue_is_acti_b326f1_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['finalizada'], name='gestion_hue_finaliz_4250e8_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['año', 'huerta'], name='gestion_hue_año_932de3_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['año', 'huerta_rentada'], name='gestion_hue_año_b443d8_idx'),
        ),
        migrations.AddIndex(
            model_name='inversioneshuerta',
            index=models.Index(fields=['fecha'], name='gestion_hue_fecha_8f8a94_idx'),
        ),
        migrations.AddIndex(
            model_name='inversioneshuerta',
            index=models.Index(fields=['categoria'], name='gestion_hue_categor_54b136_idx'),
        ),
        migrations.AddIndex(
            model_name='inversioneshuerta',
            index=models.Index(fields=['cosecha'], name='gestion_hue_cosecha_d6495e_idx'),
        ),
        migrations.AddIndex(
            model_name='inversioneshuerta',
            index=models.Index(fields=['temporada'], name='gestion_hue_tempora_acd74b_idx'),
        ),
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['nombre'], name='gestion_hue_nombre_67cfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['temporada'], name='gestion_hue_tempora_23249d_idx'),
        ),
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['is_active'], name='gestion_hue_is_acti_85d5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['temporada', 'is_active'], name='gestion_hue_tempora_fb0bd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cosecha',
            unique_together={('temporada', 'nombre')},
        ),
    ]
