# Generated by Django 5.0.6 on 2025-08-06 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosecha',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='categoriainversion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cosecha',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='gestion_huerta.temporada'),
        ),
        migrations.AlterUniqueTogether(
            name='cosecha',
            unique_together={('temporada', 'nombre')},
        ),
    ]
