# Generated by Django 5.0.6 on 2025-04-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huerta',
            name='variedades',
            field=models.CharField(max_length=255),
        ),
    ]
