# Generated by Django 5.0.6 on 2026-03-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='temporada',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('huerta__isnull', False), ('huerta_rentada__isnull', True)), models.Q(('huerta__isnull', True), ('huerta_rentada__isnull', False)), _connector='OR'), name='chk_temporada_single_origin'),
        ),
        migrations.AddConstraint(
            model_name='temporada',
            constraint=models.UniqueConstraint(condition=models.Q(('huerta__isnull', False)), fields=('año', 'huerta'), name='uniq_temporada_huerta_anio'),
        ),
        migrations.AddConstraint(
            model_name='temporada',
            constraint=models.UniqueConstraint(condition=models.Q(('huerta_rentada__isnull', False)), fields=('año', 'huerta_rentada'), name='uniq_temporada_huerta_rentada_anio'),
        ),
    ]
