# Generated by Django 5.0.6 on 2025-08-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0002_alter_cosecha_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversioneshuerta',
            name='archivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inversioneshuerta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='archivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
