# Generated by Django 5.0.6 on 2025-04-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0002_alter_huerta_variedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='archivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
