# Generated by Django 5.0.6 on 2026-03-28 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0002_temporada_chk_temporada_single_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPreCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'permissions': (('archive_categoriaprecosecha', 'Puede archivar categoria de precosecha'), ('restore_categoriaprecosecha', 'Puede restaurar categoria de precosecha')),
            },
        ),
        migrations.CreateModel(
            name='PreCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('gastos_insumos', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gastos_mano_obra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('archivado_por_cascada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'permissions': (('archive_precosecha', 'Puede archivar precosecha'), ('restore_precosecha', 'Puede restaurar precosecha')),
            },
        ),
        migrations.AlterModelOptions(
            name='categoriainversion',
            options={'ordering': ['id'], 'permissions': (('archive_categoriainversion', 'Puede archivar categoria de inversion'), ('restore_categoriainversion', 'Puede restaurar categoria de inversion'))},
        ),
        migrations.AlterModelOptions(
            name='cosecha',
            options={'ordering': ['-id'], 'permissions': (('archive_cosecha', 'Puede archivar cosecha'), ('restore_cosecha', 'Puede restaurar cosecha'), ('finalize_cosecha', 'Puede finalizar cosecha'), ('reactivate_cosecha', 'Puede reactivar cosecha'), ('exportpdf_cosecha', 'Puede exportar PDF de cosecha'), ('exportexcel_cosecha', 'Puede exportar Excel de cosecha'))},
        ),
        migrations.AlterModelOptions(
            name='huerta',
            options={'ordering': ['-id'], 'permissions': (('archive_huerta', 'Puede archivar huerta'), ('restore_huerta', 'Puede restaurar huerta'), ('exportpdf_huerta', 'Puede exportar PDF de huerta'), ('exportexcel_huerta', 'Puede exportar Excel de huerta'))},
        ),
        migrations.AlterModelOptions(
            name='huertarentada',
            options={'ordering': ['-id'], 'permissions': (('archive_huertarentada', 'Puede archivar huerta rentada'), ('restore_huertarentada', 'Puede restaurar huerta rentada'), ('exportpdf_huertarentada', 'Puede exportar PDF de huerta rentada'), ('exportexcel_huertarentada', 'Puede exportar Excel de huerta rentada'))},
        ),
        migrations.AlterModelOptions(
            name='inversioneshuerta',
            options={'ordering': ['-fecha', '-id'], 'permissions': (('archive_inversioneshuerta', 'Puede archivar inversion'), ('restore_inversioneshuerta', 'Puede restaurar inversion'))},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'ordering': ['-id'], 'permissions': (('archive_propietario', 'Puede archivar propietario'), ('restore_propietario', 'Puede restaurar propietario'))},
        ),
        migrations.AlterModelOptions(
            name='temporada',
            options={'ordering': ['-año'], 'permissions': (('archive_temporada', 'Puede archivar temporada'), ('restore_temporada', 'Puede restaurar temporada'), ('finalize_temporada', 'Puede finalizar temporada'), ('reactivate_temporada', 'Puede reactivar temporada'), ('activate_operational_temporada', 'Puede activar operacion de temporada'), ('exportpdf_temporada', 'Puede exportar PDF de temporada'), ('exportexcel_temporada', 'Puede exportar Excel de temporada'))},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta', '-id'], 'permissions': (('archive_venta', 'Puede archivar venta'), ('restore_venta', 'Puede restaurar venta'))},
        ),
        migrations.AddField(
            model_name='temporada',
            name='estado_operativo',
            field=models.CharField(choices=[('planificada', 'Planificada'), ('operativa', 'Operativa')], default='operativa', max_length=20),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['estado_operativo'], name='gestion_hue_estado__912f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_venta'], name='gestion_hue_fecha_v_ffb478_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cosecha'], name='gestion_hue_cosecha_cb1ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['temporada'], name='gestion_hue_tempora_0a6f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaprecosecha',
            index=models.Index(fields=['nombre'], name='gestion_hue_nombre_ce6456_idx'),
        ),
        migrations.AddField(
            model_name='precosecha',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precosechas', to='gestion_huerta.categoriaprecosecha'),
        ),
        migrations.AddField(
            model_name='precosecha',
            name='huerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precosechas', to='gestion_huerta.huerta'),
        ),
        migrations.AddField(
            model_name='precosecha',
            name='huerta_rentada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precosechas', to='gestion_huerta.huertarentada'),
        ),
        migrations.AddField(
            model_name='precosecha',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precosechas', to='gestion_huerta.temporada'),
        ),
        migrations.AddIndex(
            model_name='precosecha',
            index=models.Index(fields=['fecha'], name='gestion_hue_fecha_a1ea7a_idx'),
        ),
        migrations.AddIndex(
            model_name='precosecha',
            index=models.Index(fields=['categoria'], name='gestion_hue_categor_b1c990_idx'),
        ),
        migrations.AddIndex(
            model_name='precosecha',
            index=models.Index(fields=['temporada'], name='gestion_hue_tempora_0eb458_idx'),
        ),
        migrations.AddIndex(
            model_name='precosecha',
            index=models.Index(fields=['is_active'], name='gestion_hue_is_acti_a6c7a0_idx'),
        ),
    ]
