# Generated by Django 5.0.6 on 2025-08-07 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_huerta", "0003_inversioneshuerta_archivado_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriainversion",
            name="archivado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categoriainversion",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="inversioneshuerta",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inversiones",
                to="gestion_huerta.categoriainversion",
            ),
        ),
    ]
