# Generated by Django 5.0.6 on 2025-08-07 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_huerta", "0003_inversioneshuerta_archivado_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inversioneshuerta",
            name="huerta_rentada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_huerta.huertarentada",
            ),
        ),
        migrations.AlterField(
            model_name="inversioneshuerta",
            name="huerta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_huerta.huerta",
            ),
        ),
    ]
