# Generated by Django 5.0.6 on 2025-08-08 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0004_categoriainversion_archivado_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriainversion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='inversioneshuerta',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.RemoveField(
            model_name='inversioneshuerta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='inversioneshuerta',
            name='huerta_rentada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huertarentada'),
        ),
        migrations.AddField(
            model_name='inversioneshuerta',
            name='temporada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='gestion_huerta.temporada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='huerta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huerta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='temporada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='gestion_huerta.temporada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inversioneshuerta',
            name='huerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huerta'),
        ),
        migrations.AddIndex(
            model_name='categoriainversion',
            index=models.Index(fields=['nombre'], name='gestion_hue_nombre_e01821_idx'),
        ),
        migrations.AddIndex(
            model_name='inversioneshuerta',
            index=models.Index(fields=['fecha'], name='gestion_hue_fecha_8f8a94_idx'),
        ),
        migrations.AddIndex(
            model_name='inversioneshuerta',
            index=models.Index(fields=['categoria'], name='gestion_hue_categor_54b136_idx'),
        ),
        migrations.AddIndex(
            model_name='inversioneshuerta',
            index=models.Index(fields=['cosecha'], name='gestion_hue_cosecha_d6495e_idx'),
        ),
        migrations.AddIndex(
            model_name='inversioneshuerta',
            index=models.Index(fields=['temporada'], name='gestion_hue_tempora_acd74b_idx'),
        ),
    ]
