# Generated by Django 5.0.6 on 2025-05-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0004_huerta_archivado_en_huerta_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='huertarentada',
            name='archivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huertarentada',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['ubicacion'], name='gestion_hue_ubicaci_44441d_idx'),
        ),
    ]
