# Generated by Django 5.0.6 on 2025-08-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_huerta", "0004_categoriainversion_archivado_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inversioneshuerta",
            name="nombre",
        ),
        migrations.AddField(
            model_name="inversioneshuerta",
            name="temporada",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inversiones",
                to="gestion_huerta.temporada",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venta",
            name="huerta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas",
                to="gestion_huerta.huerta",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venta",
            name="temporada",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas",
                to="gestion_huerta.temporada",
            ),
            preserve_default=False,
        ),
    ]
