# Generated by Django 5.0.6 on 2025-08-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0005_alter_categoriainversion_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='huerta',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='huertarentada',
            unique_together=set(),
        ),
    ]
