# Generated by Django 5.0.6 on 2025-05-17 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0005_huertarentada_archivado_en_huertarentada_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('archivado_en', models.DateTimeField(blank=True, null=True)),
                ('huerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='gestion_huerta.huerta')),
                ('huerta_rentada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='gestion_huerta.huertarentada')),
            ],
            options={
                'ordering': ['-año'],
            },
        ),
        migrations.AddField(
            model_name='cosecha',
            name='temporada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='gestion_huerta.temporada'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['año'], name='gestion_hue_año_4727d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temporada',
            unique_together={('año', 'huerta'), ('año', 'huerta_rentada')},
        ),
    ]
