# Generated by Django 5.0.6 on 2025-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0006_temporada_cosecha_temporada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='archivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosecha',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
