# Generated by Django 5.0.6 on 2025-08-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0006_alter_huerta_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propietario',
            options={'ordering': ['-id']},
        ),
        migrations.RenameIndex(
            model_name='huerta',
            new_name='idx_huerta_nombre',
            old_name='gestion_hue_nombre_237773_idx',
        ),
        migrations.RenameIndex(
            model_name='huertarentada',
            new_name='idx_hr_nombre',
            old_name='gestion_hue_nombre_a087e3_idx',
        ),
        migrations.RenameIndex(
            model_name='huertarentada',
            new_name='idx_hr_ubicacion',
            old_name='gestion_hue_ubicaci_44441d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='huerta',
            unique_together={('nombre', 'ubicacion', 'propietario')},
        ),
        migrations.AlterUniqueTogether(
            name='huertarentada',
            unique_together={('nombre', 'ubicacion', 'propietario')},
        ),
        migrations.AddIndex(
            model_name='huerta',
            index=models.Index(fields=['archivado_en'], name='idx_huerta_archivado'),
        ),
        migrations.AddIndex(
            model_name='huerta',
            index=models.Index(fields=['is_active'], name='idx_huerta_is_active'),
        ),
        migrations.AddIndex(
            model_name='huerta',
            index=models.Index(fields=['propietario', 'archivado_en'], name='idx_huerta_prop_arch'),
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['archivado_en'], name='idx_hr_archivado'),
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['is_active'], name='idx_hr_is_active'),
        ),
        migrations.AddIndex(
            model_name='huertarentada',
            index=models.Index(fields=['propietario', 'archivado_en'], name='idx_hr_prop_arch'),
        ),
        migrations.AddIndex(
            model_name='propietario',
            index=models.Index(fields=['nombre'], name='idx_prop_nombre'),
        ),
        migrations.AddIndex(
            model_name='propietario',
            index=models.Index(fields=['apellidos'], name='idx_prop_apellidos'),
        ),
        migrations.AddIndex(
            model_name='propietario',
            index=models.Index(fields=['direccion'], name='idx_prop_direccion'),
        ),
        migrations.AddIndex(
            model_name='propietario',
            index=models.Index(fields=['is_active'], name='idx_prop_is_active'),
        ),
        migrations.AddIndex(
            model_name='propietario',
            index=models.Index(fields=['archivado_en'], name='idx_prop_archivado'),
        ),
        migrations.AddIndex(
            model_name='propietario',
            index=models.Index(fields=['nombre', 'apellidos'], name='idx_prop_nom_ape'),
        ),
    ]
