# Generated by Django 5.0.6 on 2025-08-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0007_alter_propietario_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['temporada'], name='gestion_hue_tempora_23249d_idx'),
        ),
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['is_active'], name='gestion_hue_is_acti_85d5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='cosecha',
            index=models.Index(fields=['temporada', 'is_active'], name='gestion_hue_tempora_fb0bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['huerta'], name='gestion_hue_huerta__c45966_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['huerta_rentada'], name='gestion_hue_huerta__6402a6_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['is_active'], name='gestion_hue_is_acti_b326f1_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['finalizada'], name='gestion_hue_finaliz_4250e8_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['año', 'huerta'], name='gestion_hue_año_932de3_idx'),
        ),
        migrations.AddIndex(
            model_name='temporada',
            index=models.Index(fields=['año', 'huerta_rentada'], name='gestion_hue_año_b443d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='temporada',
            constraint=models.UniqueConstraint(condition=models.Q(('huerta__isnull', False)), fields=('año', 'huerta'), name='uniq_temporada_año_huerta'),
        ),
        migrations.AddConstraint(
            model_name='temporada',
            constraint=models.UniqueConstraint(condition=models.Q(('huerta_rentada__isnull', False)), fields=('año', 'huerta_rentada'), name='uniq_temporada_año_huerta_rentada'),
        ),
    ]
