# Generated by Django 5.0.6 on 2025-06-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0007_cosecha_archivado_en_cosecha_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temporada',
            unique_together=set(),
        ),
    ]
