# Generated by Django 5.0.6 on 2025-08-12 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0008_cosecha_gestion_hue_tempora_23249d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='huerta_rentada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huertarentada'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='huerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_huerta.huerta'),
        ),
    ]
