# Generated by Django 5.0.6 on 2025-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0009_venta_huerta_rentada_alter_venta_huerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='archivado_por_cascada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inversioneshuerta',
            name='archivado_por_cascada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temporada',
            name='archivado_por_cascada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='archivado_por_cascada',
            field=models.BooleanField(default=False),
        ),
    ]
