# Generated by Django 5.0.6 on 2025-08-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0010_cosecha_archivado_por_cascada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriainversion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
