# Generated by Django 5.0.6 on 2025-08-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0011_alter_categoriainversion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
