# Generated by Django 5.0.6 on 2025-08-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_huerta', '0013_seed_extra_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huerta',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='huertarentada',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='temporada',
            name='uniq_temporada_año_huerta',
        ),
        migrations.RemoveConstraint(
            model_name='temporada',
            name='uniq_temporada_año_huerta_rentada',
        ),
    ]
