# Generated by Django 5.0.6 on 2025-04-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='archivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
