# Generated by Django 5.0.6 on 2025-08-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroactividad",
            name="ip",
        ),
    ]
