# Generated by Django 5.0.6 on 2025-06-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_users_archivado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroactividad',
            name='user_agent',
        ),
    ]
