# agroproductores_risol/settings.py
"""
Django settings for agroproductores_risol project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""

from pathlib import Path
from datetime import timedelta
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-hqq+7*v0)dyeqt(^sin=@6xvf52vux2*##m=fkqyhennl&ndr$'

DEBUG = True

# ✅ Para desarrollo local y evitar DisallowedHost
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# CORS
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite
]
CORS_ALLOW_CREDENTIALS = True
# (opcional) Si descargas archivos desde API y quieres leer nombres:
# CORS_EXPOSE_HEADERS = ["Content-Disposition"]

INSTALLED_APPS = [
    # Apps del dominio
    'gestion_usuarios',
    'gestion_huerta',
    'gestion_bodega',
    'gestion_venta',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',

    # ⚠️ Si no usas tokens legacy, podrías quitar esta app.
    # La dejo porque ya tienes tablas en BD; no estorba.
    'rest_framework.authtoken',

    # ✅ Habilita blacklist de refresh tokens (lo usamos en LogoutView)
    'rest_framework_simplejwt.token_blacklist',

    'drf_spectacular',
    'drf_spectacular_sidecar',
]

SPECTACULAR_SETTINGS = {
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    # Puedes añadir componentes de seguridad si documentas JWT en Swagger
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Middlewares personalizados
    # 'agroproductores_risol.middlewares.ip_restriction',
    'agroproductores_risol.middlewares.security.BlockInactiveUserMiddleware',
    'agroproductores_risol.middlewares.security.PreventBackAfterLogoutMiddleware',
    'agroproductores_risol.middlewares.security.RoleBasedRedirectMiddleware',
]

ROOT_URLCONF = 'agroproductores_risol.urls'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "agroproductores_risol" / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agroproductores_risol.wsgi.application'

# Base de datos (MySQL/MariaDB)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'agroproductores_risol',
        'USER': 'yahir',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# DRF + JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    # ⚠️ Asegúrate de que esta clase exista; si no, comenta el bloque THROTTLE
    "DEFAULT_THROTTLE_CLASSES": [
        "gestion_usuarios.utils.throttles.BaseUserThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "default_user": "50000/day",
        "login": "20/min",
        "sensitive_action": "50/hour",
        "admin_only": "100/day",
        "refresh_token": "20/hour",
        "permissions": "30/min",
    },

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'agroproductores_risol.utils.pagination.GenericPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Puedes dejar False. Si algún día activas rotación, la blacklist sigue funcionando.
    'ROTATE_REFRESH_TOKENS': False,

    # ✅ Necesario para que funcione blacklist
    'BLACKLIST_AFTER_ROTATION': True,

    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=60),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}

CRISPY_TEMPLATE_PACK = 'bootstrap4'
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

AUTH_USER_MODEL = 'gestion_usuarios.Users'

# (No usamos login/logout de Django en SPA, pero no estorban)
LOGOUT_REDIRECT_URL = 'gestion_usuarios:login'
LOGIN_URL = 'gestion_usuarios:login'
LOGIN_REDIRECT_URL = '/redirect_dashboard/'

# i18n
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Formato numérico
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = '.'
THOUSAND_SEPARATOR = ','
NUMBER_GROUPING = 3

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
